apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - cert-manager.yaml
  - csi-driver-nfs.yaml
  - tailscale.yaml
  - kube-vip.yaml
  - kured.yaml
  - longhorn.yaml
